### PR TITLE
Update UG

### PR DESCRIPTION
**Pull request by Chang-CH**
- Fixed incorrect text output in `edit` example
- Added expected behaviour for <0, >2147483647 indexes for `view`, `delete`, `edit`

### CODE REVIEW

**Review by nicolej2122 — APPROVED** [review]
LGTM

**Comment by yunpeng1234** [comment]
Can change FAQ seq Computer -> computer

Also maybe we can write #249 and #250  into UG

**Comment by jackgugz** [comment]
Please refer to comment listed in issue #242

**Review by jackgugz — CHANGES_REQUESTED** [review]
Please refer to comment listed in issue #242

**Pull request merged**
