### PR TITLE
Branch add message

### PR DESCRIPTION
**Pull request by yunpeng1234**
Change tag into skill for add message

Change Skill Tags names to  Skill names for error message

#255

### CODE REVIEW

**Comment by yunpeng1234** [comment]
delete and edit messages changed

**Comment by yunpeng1234** [comment]
Changed view command text also

**Review by nicolej2122 — APPROVED** [review]
LGTM

**Review by Chang-CH — APPROVED** [review]
LGTM

**Review by jackgugz — APPROVED** [review]
LGTM

**Pull request merged**
