### PR TITLE
Update DG bugs

### PR DESCRIPTION
**Pull request by Chang-CH**
See [comment](https://github.com/AY2122S1-CS2103T-F12-2/tp/issues/243#issuecomment-962450578)
Changes made:

DG review [Chang-CH](https://github.com/AY2122S1-CS2103T-F12-2/tp/issues/243#issuecomment-962450578)
- removed PUML tip
- Fixed file links
- removed fixed width line 131, 187
- fixed edit diagram file name
- added line break 205
- line 221 fixed wrong reference
- removed `more to be added`, lines 530, 563, 584, 612, 620
- removed Private contact detail from glossary
- fixed incorrect reference line 581
- Addeed save file behaviour

DG review [jackgugz](https://github.com/AY2122S1-CS2103T-F12-2/tp/issues/243#issuecomment-962460286)
-  links to all such webs are not working
- sequence diagram for edit all feature is broken
- a new line to start for the second aspect
-  non functional requirements have the line "more to be added" to be deleted before final submission

### CODE REVIEW

**Comment by yunpeng1234** [comment]
LGTM

**Review by jackgugz — CHANGES_REQUESTED** [review]
please refer to the comments in issue #243 
Please do NOT merge until all changes are settled.

**Review by yunpeng1234 — APPROVED** [review]
Lgtm

**Review by jackgugz — APPROVED** [review]
Would like to check on the unsettled comments from #243. D

**Pull request merged**
